services:
  # Manager service - can be deployed on a dedicated server
  bst-manager:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        - SERVICE_TYPE=manager
    image: bst-manager:${VERSION:-latest}
    container_name: bst-manager-${MANAGER_PORT:-8000}
    ports:
      - "${MANAGER_PORT:-8000}:${MANAGER_PORT:-8000}"
    volumes:
      - ../.env:/app/.env
      - ~/.bittensor:/root/.bittensor
      - ./logs:/app/logs
    environment:
      - MANAGER_PORT=${MANAGER_PORT:-8000}
      - BT_SUBTENSOR_CHAIN_ENDPOINT=${CHAIN_ENDPOINT:-ws://host.docker.internal:9944}
    restart: unless-stopped
    # Resource limits optimized for 4-core 8GB system
    deploy:
      resources:
        limits:
          memory: ${MEMORY_LIMIT:-2G}
          cpus: ${CPU_LIMIT:-1}
        reservations:
          memory: ${MEMORY_RESERVATION:-512M}
          cpus: ${CPU_RESERVATION:-0.25}
    # File descriptor limits
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
      nproc:
        soft: 32768
        hard: 32768
    # Security options
    security_opt:
      - no-new-privileges:true
    # Health check with shorter intervals
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${MANAGER_PORT:-8000}/health"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 30s